[general]
trace_instructions = false
start_pc = 0x80000000

[system]
uart_base = 0x10000000
disk_base = 0x90000000
ram_base = 0x80000000
syscon_base = 0x100000

[memory]
ram_size = 0x08000000
controller = "Simple"
row_miss_latency = 150
tlb_size = 32

[cache.l1_i]
enabled = true
size_bytes = 4096
line_bytes = 64
ways = 1
policy = "LRU"
latency = 1
prefetcher = "None"
prefetch_table_size = 0
prefetch_degree = 0

[cache.l1_d]
enabled = true
size_bytes = 4096
line_bytes = 64
ways = 1
policy = "LRU"
latency = 1
prefetcher = "None"
prefetch_table_size = 0
prefetch_degree = 0

[cache.l2]
enabled = false

[cache.l3]
enabled = false

[pipeline]
branch_predictor = "Static"
width = 1
btb_size = 512
ras_size = 8
