[general]
trace_instructions =  false
start_pc = 0x80000000

[system]
uart_base = 0x10000000
disk_base = 0x90000000
ram_base = 0x80000000

[memory]
ram_size = 0x08000000 # 128MB
controller = "DRAM"
t_cas = 15
t_ras = 35
t_pre = 15
tlb_size = 64

[cache.l1_i]
enabled = true
size_bytes = 16384 # 16KB
line_bytes = 64
ways = 4
policy = "LRU"
latency = 1
prefetcher = "NextLine"
prefetch_degree = 1

[cache.l1_d]
enabled = true
size_bytes = 16384
line_bytes = 64
ways = 4
policy = "LRU"
latency = 1
prefetcher = "NextLine"
prefetch_degree = 1

[cache.l2]
enabled = true
size_bytes = 262144 # 256KB
line_bytes = 64
ways = 8
policy = "LRU"
latency = 10
prefetcher = "None"
prefetch_table_size = 0
prefetch_degree = 0

[cache.l3]
enabled = false

[pipeline]
branch_predictor = "Perceptron"
width = 2
btb_size = 1024
ras_size = 16

[pipeline.perceptron]
history_length = 40
table_bits = 10
